name: Deploy to ECS

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write    # Needed for OIDC
  contents: read     # Needed for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::289956717103:role/cicd
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t subscription-service:latest .

      - name: Tag image
        run: |
          docker tag subscription-service:latest ${{ secrets.ECR_REPO }}:latest

      - name: Push image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO }}:latest

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --force-new-deployment
